version: '3.3'
# must be 3.3 

services:
  create:
    build: .
    volumes:
      - ./:/work:cached
    working_dir: /work
    command: bash /opt/nuxt-create.sh
    # nuxi init work && cd work && yarn add bootstrap @popperjs/core bootstrap-icons

  dev:
    build: .
    volumes:
      - ./work:/work:cached
    working_dir: /work
    ports:
      - "3000:3000"
    # for HMR
      - "24678:24678"
    environment:
      - HOST=0.0.0.0
      - port=3000
    # for HMR
      - CHOKIDAR_USEPOLLING=true
    command: yarn dev

  sh:
    build: .
    volumes:
      - ./work:/work:cached
      # for firebase init
      - ./docker/bin/:/root/.cache:cached
      - ./docker/config/:/root/.config:cached
    working_dir: /work
    tty: true
  
  emu:
    build: .
    volumes:
      - ./work:/work:cached
      # for firebase emulators
      - ./docker/bin/:/root/.cache:cached
      - ./docker/config/:/root/.config:cached
    working_dir: /work
    ports:
      # for emulators
      - "5001:5001"
      - "9099:9099"
      - "8080:8080"
      - "5000:5000"
      - "9199:9199"
      - "4000:4000"
      - "4400:4400"
      - "4500:4500"
    command: firebase emulators:start



